### ISSUE TITLE
User flow into COAM (once reporting finished)

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-obps#284]
A user has finished up in the reporting module. What happens when they want access to COAM? 

- [ ] What does the user flow after finishing reporting look like into COAM?

**Comment by zoeyli-46** [comment]
Closing this: the decision currently is that there will be a COAM tile on the dashboard which is locked until reporting is over, because we do not want operators to make compliance obligation payments until their report is finalized (since the reporting emissions summary determines the compliance obligation amount).
